### PR TITLE
Fix/fix and document nil pointer conversion

### LINKED ISSUE #291: Document and implement wrapper-to-v2 conversions
https://github.com/nspcc-dev/neofs-api-go/issues/288 revealed unexpected results of converting message wrappers into message structures of NeoFS API v2.

For example, some `nil` slices sometimes spawn zerolen slices. It was not somehow stipulated, but it also did not turn out to be the expected behavior.

In https://github.com/nspcc-dev/neofs-api-go/pull/289 local issues were fixed, but for several types of message wrappers.  For all similar types, carry out the following:

- convert `nil` message wrapper to `nil` (prevent panic);
- document default values set by `New...` constructors;
- make `ToV2` converters to do `nil`-to-`nil` for all reference types;
- assert all expected values in unit tests.

### PR DESCRIPTION
**Pull request by carpawell**
- closes #291
- SDK version was bumped

### CODE REVIEW

File: pkg/checksum.go [hunk 1]
```diff
@@ -28,13 +28,19 @@ const (
...
 
-// NewVersion creates and initializes blank Version.
+// NewChecksum creates and initializes blank Checksum.
+//
+// Works similar as NewChecksumFromV2(new(Checksum)).
 //
-// Works similar as NewVersionFromV2(new(Version)).
+// Defaults:
+// 	- sum: nil;
+//	- type: UnknownChecksum;
```
Comment (cthulhu-rider) [inline pkg/checksum.go:43]:
```suggestion
//	- type: ChecksumUnknown.
```

File: pkg/checksum_test.go [hunk 2]
```diff
@@ -99,3 +99,35 @@ func TestChecksumEncoding(t *testing.T) {
...
+		chs := NewChecksum()
+
+		// check initial values
+		require.Equal(t, uint32(refs.UnknownChecksum), uint32(chs.Type()))
+		require.Nil(t, chs.Sum())
+
+		// convert to v2 message
+		chsV2 := chs.ToV2()
+
+		require.Equal(t, uint32(refs.UnknownChecksum), uint32(chsV2.GetType()))
```
Comment (cthulhu-rider) [inline pkg/checksum_test.go:130]:
```suggestion
		require.Equal(t, refs.UnknownChecksum, chsV2.GetType())
```

File: pkg/checksum_test.go [hunk 3]
```diff
@@ -99,3 +99,35 @@ func TestChecksumEncoding(t *testing.T) {
...
+		require.Nil(t, x.ToV2())
+	})
+}
+
+func TestNewChecksum(t *testing.T) {
+	t.Run("default values", func(t *testing.T) {
+		chs := NewChecksum()
+
+		// check initial values
+		require.Equal(t, uint32(refs.UnknownChecksum), uint32(chs.Type()))
```
Comment (cthulhu-rider) [inline pkg/checksum_test.go:124]:
```suggestion
		require.Equal(t, ChecksumUnknown, chs.Type())
```

File: pkg/container/container_test.go [hunk 4]
```diff
@@ -91,3 +91,44 @@ func TestContainer_Signature(t *testing.T) {
...
+
+		// check initial values
+		require.Nil(t, cnt.SessionToken())
+		require.Nil(t, cnt.Signature())
+		require.Nil(t, cnt.Version())
+		require.Nil(t, cnt.Attributes())
+		require.Nil(t, cnt.PlacementPolicy())
+		require.Nil(t, cnt.OwnerID())
+
+		require.Equal(t, uint32(acl.PrivateBasicRule), cnt.BasicACL())
```
Comment (cthulhu-rider) [inline pkg/container/container_test.go:113]:
```suggestion
		require.EqualValues(t, acl.PrivateBasicRule, cnt.BasicACL())
```

File: pkg/netmap/filter_test.go [hunk 5]
```diff
@@ -295,3 +307,25 @@ func TestFilterEncoding(t *testing.T) {
...
+		require.Zero(t, filter.Operation())
+		require.Nil(t, filter.InnerFilters())
+
+		// convert to v2 message
+		filterV2 := filter.ToV2()
+
+		require.Empty(t, filterV2.GetName())
+		require.Empty(t, filterV2.GetKey())
+		require.Empty(t, filterV2.GetValue())
+		require.Zero(t, filterV2.GetOp())
```
Comment (cthulhu-rider) [inline pkg/netmap/filter_test.go:328]:
```suggestion
		require.Equal(t, netmap.UnspecifiedOperation, filterV2.GetOp())
```

File: pkg/netmap/node_info.go [hunk 6]
```diff
@@ -188,16 +188,25 @@ func (s NodeState) String() string {
 }
 
 // NewNodeAttribute creates and returns new NodeAttribute instance.
+//
+// Defaults:
+//  - key: "";
+//	- value: "";
```
Comment (cthulhu-rider) [inline pkg/netmap/node_info.go:194]: Moved out or github jokes (and pls check out all same places)

File: pkg/netmap/node_info_test.go [hunk 7]
```diff
@@ -31,14 +31,30 @@ func TestNodeStateFromV2(t *testing.T) {
...
-	aV2.SetParents([]string{"par1", "par2"})
+	t.Run("from nil", func(t *testing.T) {
+		var x *netmap.Attribute
 
-	a := NewNodeAttributeFromV2(aV2)
+		require.Nil(t, NewNodeAttributeFromV2(x))
+	})
+
+	t.Run("from non-nil", func(t *testing.T) {
+		aV2 := new(netmap.Attribute)
```
Comment (cthulhu-rider) [inline pkg/netmap/node_info_test.go:41]: Pls use generator

File: pkg/netmap/node_info_test.go [hunk 8]
```diff
@@ -78,18 +94,34 @@ func testNodeAttribute() *NodeAttribute {
...
-		testNodeAttribute().ToV2(),
+	t.Run("from nil", func(t *testing.T) {
+		var x *netmap.NodeInfo
+
+		require.Nil(t, NewNodeInfoFromV2(x))
 	})
 
-	i := NewNodeInfoFromV2(iV2)
+	t.Run("from non-nil", func(t *testing.T) {
+		iV2 := new(netmap.NodeInfo)
```
Comment (cthulhu-rider) [inline pkg/netmap/node_info_test.go:104]: Pls use generator

File: pkg/netmap/node_info_test.go [hunk 9]
```diff
@@ -179,3 +211,41 @@ func TestNodeInfoEncoding(t *testing.T) {
...
+		require.Nil(t, attrV2.GetParents())
+	})
+}
+
+func TestNewNodeInfo(t *testing.T) {
+	t.Run("default values", func(t *testing.T) {
+		ni := NewNodeInfo()
+
+		// check initial values
+		require.Empty(t, ni.PublicKey())
```
Comment (cthulhu-rider) [inline pkg/netmap/node_info_test.go:238]:
```suggestion
		require.Nil(t, ni.PublicKey())
```
Empty slice is empty too

File: pkg/netmap/node_info_test.go [hunk 10]
```diff
@@ -179,3 +211,41 @@ func TestNodeInfoEncoding(t *testing.T) {
...
+		require.Empty(t, ni.Address())
+		require.Nil(t, ni.Attributes())
+		require.Zero(t, ni.State())
+
+		// convert to v2 message
+		niV2 := ni.ToV2()
+
+		require.Empty(t, niV2.GetPublicKey())
```
Comment (cthulhu-rider) [inline pkg/netmap/node_info_test.go:246]: Same

File: pkg/netmap/node_info_test.go [hunk 11]
```diff
@@ -179,3 +211,41 @@ func TestNodeInfoEncoding(t *testing.T) {
...
+		require.Empty(t, niV2.GetAddress())
+		require.Nil(t, niV2.GetAttributes())
+		require.Zero(t, niV2.GetState())
```
Comment (cthulhu-rider) [inline pkg/netmap/node_info_test.go:249]:
```suggestion
		require.Equal(t, netmap.UnspecifiedState, niV2.GetState())
```

File: pkg/netmap/policy_test.go [hunk 12]
```diff
@@ -144,3 +144,39 @@ func TestPlacementPolicyEncoding(t *testing.T) {
...
 }
+
+func TestNewPlacementPolicy(t *testing.T) {
+	t.Run("nil", func(t *testing.T) {
+		var x *PlacementPolicy
+
+		require.Nil(t, x.ToV2())
+	})
+
+	t.Run("defaults", func(t *testing.T) {
```
Comment (cthulhu-rider) [inline pkg/netmap/policy_test.go:155]: Redundant I guess

File: pkg/netmap/replica_test.go [hunk 13]
```diff
@@ -16,13 +16,21 @@ func testReplica() *Replica {
...
-	rV2.SetSelector("selector")
+	t.Run("from nil", func(t *testing.T) {
+		var x *netmap.Replica
 
-	r := NewReplicaFromV2(rV2)
+		require.Nil(t, NewReplicaFromV2(x))
+	})
+
+	t.Run("from non-nil", func(t *testing.T) {
+		rV2 := new(netmap.Replica)
```
Comment (cthulhu-rider) [inline pkg/netmap/replica_test.go:26]: Pls use generator

File: pkg/netmap/selector.go [hunk 14]
```diff
@@ -156,16 +156,27 @@ func (c *Context) getSelectionBase(s *Selector) []nodeAttrPair {
 }
 
 // NewSelector creates and returns new Selector instance.
+//
+// Defaults:
+//  - name: "";
+//  - attribute: "";
+//  - filter: "";
+//  - clause: 0;
```
Comment (cthulhu-rider) [inline pkg/netmap/selector.go:164]:
```suggestion
//  - clause: ClauseUnspecified;
```

File: pkg/netmap/selector_test.go [hunk 15]
```diff
@@ -495,3 +482,54 @@ func TestSelectorEncoding(t *testing.T) {
...
+
+func TestNewSelectorFromV2(t *testing.T) {
+	t.Run("from nil", func(t *testing.T) {
+		var x *netmap.Selector
+
+		require.Nil(t, NewSelectorFromV2(x))
+	})
+
+	t.Run("from non-nil", func(t *testing.T) {
+		sV2 := new(netmap.Selector)
```
Comment (cthulhu-rider) [inline pkg/netmap/selector_test.go:502]: Pls use generator

File: pkg/netmap/selector_test.go [hunk 16]
```diff
@@ -495,3 +482,54 @@ func TestSelectorEncoding(t *testing.T) {
...
+	})
+}
+
+func TestNewSelector(t *testing.T) {
+	t.Run("default values", func(t *testing.T) {
+		s := NewSelector()
+
+		// check initial values
+		require.Zero(t, s.Count())
+		require.Zero(t, s.Clause())
```
Comment (cthulhu-rider) [inline pkg/netmap/selector_test.go:521]:
```suggestion
		require.Equal(t, ClauseUnspecified, s.Clause())
```

File: pkg/netmap/selector_test.go [hunk 17]
```diff
@@ -495,3 +482,54 @@ func TestSelectorEncoding(t *testing.T) {
...
+		require.Empty(t, s.Attribute())
+		require.Empty(t, s.Name())
+		require.Empty(t, s.Filter())
+
+		// convert to v2 message
+		sV2 := s.ToV2()
+
+		require.Zero(t, sV2.GetCount())
+		require.Zero(t, sV2.GetClause())
```
Comment (cthulhu-rider) [inline pkg/netmap/selector_test.go:530]:
```suggestion
		require.Equal(t, netmap.UnspecifiedClause, sV2.GetClause())
```

File: pkg/object/id_test.go [hunk 18]
```diff
@@ -107,3 +108,33 @@ func TestObjectIDEncoding(t *testing.T) {
...
+		require.Nil(t, x.ToV2())
+	})
+}
+
+func TestNewID(t *testing.T) {
+	t.Run("default values", func(t *testing.T) {
+		id := NewID()
+
+		// check initial values
+		require.Empty(t, id.String())
```
Comment (cthulhu-rider) [inline pkg/object/id_test.go:133]: Same as for `cid.ID`

File: pkg/owner/id_test.go [hunk 19]
```diff
@@ -99,3 +100,33 @@ func TestID_Equal(t *testing.T) {
...
+		require.Nil(t, x.ToV2())
+	})
+}
+
+func TestNewID(t *testing.T) {
+	t.Run("default values", func(t *testing.T) {
+		id := NewID()
+
+		// check initial values
+		require.Empty(t, id.String())
```
Comment (cthulhu-rider) [inline pkg/owner/id_test.go:125]: Same as for `cid.ID`

File: pkg/reputation/peer_test.go [hunk 20]
```diff
@@ -50,3 +59,25 @@ func TestPeerIDEncoding(t *testing.T) {
...
+		require.Nil(t, reputation.PeerIDFromV2(x))
+	})
+}
+
+func TestNewPeerID(t *testing.T) {
+	t.Run("default values", func(t *testing.T) {
+		id := reputation.NewPeerID()
+
+		// check initial values
+		require.Empty(t, id.String())
```
Comment (cthulhu-rider) [inline pkg/reputation/peer_test.go:76]: Same as for `cid.ID`

File: pkg/reputation/trust.go [hunk 21]
```diff
@@ -185,7 +201,8 @@ type GlobalTrust reputation.GlobalTrust
 
 // NewGlobalTrust creates and returns blank GlobalTrust.
 //
-// Version is initialized to current library version.
+// Defaults:
+// 	- version: pkg.SDKVersion().
```
Comment (cthulhu-rider) [inline pkg/reputation/trust.go:205]: Add `manager` and `trust`. Cover in test

File: pkg/reputation/trust_test.go [hunk 22]
```diff
@@ -150,3 +151,92 @@ func TestGlobalTrust(t *testing.T) {
...
+		trust := reputation.NewPeerToPeerTrust()
+
+		// check initial values
+		require.Nil(t, trust.Trust())
+		require.Nil(t, trust.TrustingPeer())
+
+		// convert to v2 message
+		trustV2 := trust.ToV2()
+
+		require.Zero(t, trustV2.GetTrust())
```
Comment (cthulhu-rider) [inline pkg/reputation/trust_test.go:230]:
```suggestion
		require.Nil(t, trustV2.GetTrust())
```

File: pkg/session/session_test.go [hunk 23]
```diff
@@ -162,3 +163,45 @@ func TestToken_Iat(t *testing.T) {
...
+		require.Nil(t, token.ID())
+		require.Zero(t, token.Exp())
+		require.Zero(t, token.Iat())
+		require.Zero(t, token.Nbf())
+
+		// convert to v2 message
+		tokenV2 := token.ToV2()
+
+		require.Nil(t, tokenV2.GetSignature())
+		require.Nil(t, tokenV2.GetBody().GetOwnerID())
```
Comment (cthulhu-rider) [inline pkg/session/session_test.go:200]: I guess `require.Nil(t, tokenV2.GetBody())` is enough for all values.

File: pkg/token/bearer.go [hunk 24]
```diff
@@ -92,6 +99,12 @@ func (b *BearerToken) Issuer() *owner.ID {
 	return owner.NewIDFromNeo3Wallet(wallet)
 }
 
+// NewBearerToken creates and initializes blank BearerToken.
+//
+// Defaults:
+// 	- token: acl.BearerToken{
```
Comment (cthulhu-rider) [inline pkg/token/bearer.go:105]: You need to list all the fields .

**Review by cthulhu-rider — CHANGES_REQUESTED** [review]

**Comment by cthulhu-rider** [comment]
Forgotten docs and/or tests for `XXXFromV2` constructors:

- `audit.Result`;
- `container.UsedSpaceAnnouncement`;
- `container.NewAttributesFromV2`;
- `object.SplitID`;
- `token.NewBearerTokenFromV2`;

**Comment by carpawell** [comment]
@cthulhu-rider, added comments/tests to `XXXFromV2` of:
- `audit.Result`;
- `container.UsedSpaceAnnouncement`;
- `container.NewAttributesFromV2`.

but not for:
- `object.SplitID`;
- `token.NewBearerTokenFromV2`.

`SplitID`: i found it strange to `XXXFromV2` from `[]byte`
`BearerToken` has [logic](https://github.com/nspcc-dev/neofs-api-go/blob/master/pkg/token/bearer.go#L104) with checking if passed v2 is nil or not, so i kept that behavior

File: pkg/container/id/id.go [hunk 25]
```diff
@@ -18,6 +18,9 @@ func NewFromV2(idV2 *refs.ContainerID) *ID {
 }
 
 // New creates and initializes blank ID.
+//
+// Defaults:
+//  - value: "".
```
[the remark this answers is not in the document]
Comment (cthulhu-rider) [reply pkg/container/id/id.go:25]: We still doc that `value: nil` since this type is a reflection of API message, and everyone will understand it. But type don't provide getter of the value, so we just don't need to cover it in unit test and test only `ToV2`. Stringer is also implemented, but if you want to underline that `(*ID)(nil).String() == ""` then it's better to do it in `String` method's doc and cover in dedicated test.

[the remark this answers is not in the document]
Comment (carpawell) [reply pkg/container/id/id.go]: changed default value to `nil` in comment

File: pkg/reputation/peer_test.go (hunk 20 above)
Comment (carpawell) [reply pkg/reputation/peer_test.go]: fixed

**Review by cthulhu-rider — APPROVED** [review]

**Review by alexvanin — APPROVED** [review]
